# set starting directory - assumes test and train are in subdirectories
#setwd("/Users/DDalton/Documents/Coursera/R/getandcleandata/project")
# codebook example: https://gist.github.com/JorisSchut/dbc1fc0402f28cad9b41
# open all the files
X_test <- read.table("~/test/X_test.txt", quote="\"", comment.char="")
X_train <- read.table("~/train/X_train.txt", quote="\"", comment.char="")
y_test <- read.table("~/test/y_test.txt", quote="\"", comment.char="")
y_train <- read.table("~/train/y_train.txt", quote="\"", comment.char="")
features <- read.table("~/features.txt", quote="\"", comment.char="")
activity_labels <- read.table("~/activity_labels.txt", quote="\"", comment.char="")
subject_test <- read.table("~/test/subject_test.txt", quote="\"", comment.char="")
subject_train <- read.table("~/train/subject_train.txt", quote="\"", comment.char="")
# label activity_labels columns
colnames(activity_labels) <- c("activity","activity_name")
# make the column names as describes in features.txt become the column names for X_test
colnames(X_test) <- features[,2]
# make the column names as describes in features.txt become the column names for X_train
colnames(X_train) <- features[,2]
#add y_test activities in another column in X_test
X_test[,"activity"] <- y_test
#add y_train activities in another column in X_train
X_train[,"activity"] <- y_train
#add subject_test subject in another column in X_test
X_test[,"subject"] <- subject_test
#add subject_train subject in another column in X_train
X_train[,"subject"] <- subject_train
# join x_test and X_train vertically with rbind
x_data <- rbind(X_test,X_train)
# lookup activity label with activity column to put descriptive name on row
x_data <- merge(x_data,activity_labels,by="activity")
# delete all the columns that are not max or mean values
x_data[[555]] <-  NULL
x_data[[554]] <-  NULL
x_data[[552]] <-  NULL
x_data[[551]] <-  NULL
x_data[[550]] <-  NULL
x_data[[549]] <-  NULL
x_data[[548]] <-  NULL
x_data[[547]] <-  NULL
x_data[[546]] <-  NULL
x_data[[545]] <-  NULL
x_data[[542]] <-  NULL
x_data[[541]] <-  NULL
x_data[[539]] <-  NULL
x_data[[538]] <-  NULL
x_data[[537]] <-  NULL
x_data[[536]] <-  NULL
x_data[[535]] <-  NULL
x_data[[534]] <-  NULL
x_data[[533]] <-  NULL
x_data[[532]] <-  NULL
x_data[[529]] <-  NULL
x_data[[528]] <-  NULL
x_data[[526]] <-  NULL
x_data[[525]] <-  NULL
x_data[[524]] <-  NULL
x_data[[523]] <-  NULL
x_data[[522]] <-  NULL
x_data[[521]] <-  NULL
x_data[[520]] <-  NULL
x_data[[519]] <-  NULL
x_data[[516]] <-  NULL
x_data[[515]] <-  NULL
x_data[[513]] <-  NULL
x_data[[512]] <-  NULL
x_data[[511]] <-  NULL
x_data[[510]] <-  NULL
x_data[[509]] <-  NULL
x_data[[508]] <-  NULL
x_data[[507]] <-  NULL
x_data[[506]] <-  NULL
x_data[[503]] <-  NULL
x_data[[502]] <-  NULL
x_data[[501]] <-  NULL
x_data[[500]] <-  NULL
x_data[[499]] <-  NULL
x_data[[498]] <-  NULL
x_data[[497]] <-  NULL
x_data[[496]] <-  NULL
x_data[[495]] <-  NULL
x_data[[494]] <-  NULL
x_data[[493]] <-  NULL
x_data[[492]] <-  NULL
x_data[[491]] <-  NULL
x_data[[490]] <-  NULL
x_data[[489]] <-  NULL
x_data[[488]] <-  NULL
x_data[[487]] <-  NULL
x_data[[486]] <-  NULL
x_data[[485]] <-  NULL
x_data[[484]] <-  NULL
x_data[[483]] <-  NULL
x_data[[482]] <-  NULL
x_data[[481]] <-  NULL
x_data[[480]] <-  NULL
x_data[[479]] <-  NULL
x_data[[478]] <-  NULL
x_data[[477]] <-  NULL
x_data[[476]] <-  NULL
x_data[[475]] <-  NULL
x_data[[474]] <-  NULL
x_data[[473]] <-  NULL
x_data[[472]] <-  NULL
x_data[[471]] <-  NULL
x_data[[470]] <-  NULL
x_data[[469]] <-  NULL
x_data[[468]] <-  NULL
x_data[[467]] <-  NULL
x_data[[466]] <-  NULL
x_data[[465]] <-  NULL
x_data[[464]] <-  NULL
x_data[[463]] <-  NULL
x_data[[462]] <-  NULL
x_data[[461]] <-  NULL
x_data[[460]] <-  NULL
x_data[[459]] <-  NULL
x_data[[458]] <-  NULL
x_data[[457]] <-  NULL
x_data[[456]] <-  NULL
x_data[[452]] <-  NULL
x_data[[451]] <-  NULL
x_data[[450]] <-  NULL
x_data[[449]] <-  NULL
x_data[[448]] <-  NULL
x_data[[447]] <-  NULL
x_data[[446]] <-  NULL
x_data[[445]] <-  NULL
x_data[[444]] <-  NULL
x_data[[443]] <-  NULL
x_data[[442]] <-  NULL
x_data[[441]] <-  NULL
x_data[[440]] <-  NULL
x_data[[439]] <-  NULL
x_data[[438]] <-  NULL
x_data[[437]] <-  NULL
x_data[[436]] <-  NULL
x_data[[435]] <-  NULL
x_data[[434]] <-  NULL
x_data[[433]] <-  NULL
x_data[[432]] <-  NULL
x_data[[431]] <-  NULL
x_data[[424]] <-  NULL
x_data[[423]] <-  NULL
x_data[[422]] <-  NULL
x_data[[421]] <-  NULL
x_data[[420]] <-  NULL
x_data[[419]] <-  NULL
x_data[[418]] <-  NULL
x_data[[417]] <-  NULL
x_data[[416]] <-  NULL
x_data[[415]] <-  NULL
x_data[[414]] <-  NULL
x_data[[413]] <-  NULL
x_data[[412]] <-  NULL
x_data[[411]] <-  NULL
x_data[[410]] <-  NULL
x_data[[409]] <-  NULL
x_data[[408]] <-  NULL
x_data[[407]] <-  NULL
x_data[[406]] <-  NULL
x_data[[405]] <-  NULL
x_data[[404]] <-  NULL
x_data[[403]] <-  NULL
x_data[[402]] <-  NULL
x_data[[401]] <-  NULL
x_data[[400]] <-  NULL
x_data[[399]] <-  NULL
x_data[[398]] <-  NULL
x_data[[397]] <-  NULL
x_data[[396]] <-  NULL
x_data[[395]] <-  NULL
x_data[[394]] <-  NULL
x_data[[393]] <-  NULL
x_data[[392]] <-  NULL
x_data[[391]] <-  NULL
x_data[[390]] <-  NULL
x_data[[389]] <-  NULL
x_data[[388]] <-  NULL
x_data[[387]] <-  NULL
x_data[[386]] <-  NULL
x_data[[385]] <-  NULL
x_data[[384]] <-  NULL
x_data[[383]] <-  NULL
x_data[[382]] <-  NULL
x_data[[381]] <-  NULL
x_data[[380]] <-  NULL
x_data[[379]] <-  NULL
x_data[[378]] <-  NULL
x_data[[377]] <-  NULL
x_data[[373]] <-  NULL
x_data[[372]] <-  NULL
x_data[[371]] <-  NULL
x_data[[370]] <-  NULL
x_data[[369]] <-  NULL
x_data[[368]] <-  NULL
x_data[[367]] <-  NULL
x_data[[366]] <-  NULL
x_data[[365]] <-  NULL
x_data[[364]] <-  NULL
x_data[[363]] <-  NULL
x_data[[362]] <-  NULL
x_data[[361]] <-  NULL
x_data[[360]] <-  NULL
x_data[[359]] <-  NULL
x_data[[358]] <-  NULL
x_data[[357]] <-  NULL
x_data[[356]] <-  NULL
x_data[[355]] <-  NULL
x_data[[354]] <-  NULL
x_data[[353]] <-  NULL
x_data[[352]] <-  NULL
x_data[[345]] <-  NULL
x_data[[344]] <-  NULL
x_data[[343]] <-  NULL
x_data[[342]] <-  NULL
x_data[[341]] <-  NULL
x_data[[340]] <-  NULL
x_data[[339]] <-  NULL
x_data[[338]] <-  NULL
x_data[[337]] <-  NULL
x_data[[336]] <-  NULL
x_data[[335]] <-  NULL
x_data[[334]] <-  NULL
x_data[[333]] <-  NULL
x_data[[332]] <-  NULL
x_data[[331]] <-  NULL
x_data[[330]] <-  NULL
x_data[[329]] <-  NULL
x_data[[328]] <-  NULL
x_data[[327]] <-  NULL
x_data[[326]] <-  NULL
x_data[[325]] <-  NULL
x_data[[324]] <-  NULL
x_data[[323]] <-  NULL
x_data[[322]] <-  NULL
x_data[[321]] <-  NULL
x_data[[320]] <-  NULL
x_data[[319]] <-  NULL
x_data[[318]] <-  NULL
x_data[[317]] <-  NULL
x_data[[316]] <-  NULL
x_data[[315]] <-  NULL
x_data[[314]] <-  NULL
x_data[[313]] <-  NULL
x_data[[312]] <-  NULL
x_data[[311]] <-  NULL
x_data[[310]] <-  NULL
x_data[[309]] <-  NULL
x_data[[308]] <-  NULL
x_data[[307]] <-  NULL
x_data[[306]] <-  NULL
x_data[[305]] <-  NULL
x_data[[304]] <-  NULL
x_data[[303]] <-  NULL
x_data[[302]] <-  NULL
x_data[[301]] <-  NULL
x_data[[300]] <-  NULL
x_data[[299]] <-  NULL
x_data[[298]] <-  NULL
x_data[[294]] <-  NULL
x_data[[293]] <-  NULL
x_data[[292]] <-  NULL
x_data[[291]] <-  NULL
x_data[[290]] <-  NULL
x_data[[289]] <-  NULL
x_data[[288]] <-  NULL
x_data[[287]] <-  NULL
x_data[[286]] <-  NULL
x_data[[285]] <-  NULL
x_data[[284]] <-  NULL
x_data[[283]] <-  NULL
x_data[[282]] <-  NULL
x_data[[281]] <-  NULL
x_data[[280]] <-  NULL
x_data[[279]] <-  NULL
x_data[[278]] <-  NULL
x_data[[277]] <-  NULL
x_data[[276]] <-  NULL
x_data[[275]] <-  NULL
x_data[[274]] <-  NULL
x_data[[273]] <-  NULL
x_data[[266]] <-  NULL
x_data[[265]] <-  NULL
x_data[[264]] <-  NULL
x_data[[263]] <-  NULL
x_data[[262]] <-  NULL
x_data[[261]] <-  NULL
x_data[[260]] <-  NULL
x_data[[259]] <-  NULL
x_data[[258]] <-  NULL
x_data[[257]] <-  NULL
x_data[[256]] <-  NULL
x_data[[253]] <-  NULL
x_data[[252]] <-  NULL
x_data[[251]] <-  NULL
x_data[[250]] <-  NULL
x_data[[249]] <-  NULL
x_data[[248]] <-  NULL
x_data[[247]] <-  NULL
x_data[[246]] <-  NULL
x_data[[245]] <-  NULL
x_data[[244]] <-  NULL
x_data[[243]] <-  NULL
x_data[[240]] <-  NULL
x_data[[239]] <-  NULL
x_data[[238]] <-  NULL
x_data[[237]] <-  NULL
x_data[[236]] <-  NULL
x_data[[235]] <-  NULL
x_data[[234]] <-  NULL
x_data[[233]] <-  NULL
x_data[[232]] <-  NULL
x_data[[231]] <-  NULL
x_data[[230]] <-  NULL
x_data[[227]] <-  NULL
x_data[[226]] <-  NULL
x_data[[225]] <-  NULL
x_data[[224]] <-  NULL
x_data[[223]] <-  NULL
x_data[[222]] <-  NULL
x_data[[221]] <-  NULL
x_data[[220]] <-  NULL
x_data[[219]] <-  NULL
x_data[[218]] <-  NULL
x_data[[217]] <-  NULL
x_data[[214]] <-  NULL
x_data[[213]] <-  NULL
x_data[[212]] <-  NULL
x_data[[211]] <-  NULL
x_data[[210]] <-  NULL
x_data[[209]] <-  NULL
x_data[[208]] <-  NULL
x_data[[207]] <-  NULL
x_data[[206]] <-  NULL
x_data[[205]] <-  NULL
x_data[[204]] <-  NULL
x_data[[201]] <-  NULL
x_data[[200]] <-  NULL
x_data[[199]] <-  NULL
x_data[[198]] <-  NULL
x_data[[197]] <-  NULL
x_data[[196]] <-  NULL
x_data[[195]] <-  NULL
x_data[[194]] <-  NULL
x_data[[193]] <-  NULL
x_data[[192]] <-  NULL
x_data[[191]] <-  NULL
x_data[[190]] <-  NULL
x_data[[189]] <-  NULL
x_data[[188]] <-  NULL
x_data[[187]] <-  NULL
x_data[[186]] <-  NULL
x_data[[185]] <-  NULL
x_data[[184]] <-  NULL
x_data[[183]] <-  NULL
x_data[[182]] <-  NULL
x_data[[181]] <-  NULL
x_data[[180]] <-  NULL
x_data[[179]] <-  NULL
x_data[[178]] <-  NULL
x_data[[177]] <-  NULL
x_data[[176]] <-  NULL
x_data[[175]] <-  NULL
x_data[[174]] <-  NULL
x_data[[173]] <-  NULL
x_data[[172]] <-  NULL
x_data[[171]] <-  NULL
x_data[[170]] <-  NULL
x_data[[169]] <-  NULL
x_data[[168]] <-  NULL
x_data[[161]] <-  NULL
x_data[[160]] <-  NULL
x_data[[159]] <-  NULL
x_data[[158]] <-  NULL
x_data[[157]] <-  NULL
x_data[[156]] <-  NULL
x_data[[155]] <-  NULL
x_data[[154]] <-  NULL
x_data[[153]] <-  NULL
x_data[[152]] <-  NULL
x_data[[151]] <-  NULL
x_data[[150]] <-  NULL
x_data[[149]] <-  NULL
x_data[[148]] <-  NULL
x_data[[147]] <-  NULL
x_data[[146]] <-  NULL
x_data[[145]] <-  NULL
x_data[[144]] <-  NULL
x_data[[143]] <-  NULL
x_data[[142]] <-  NULL
x_data[[141]] <-  NULL
x_data[[140]] <-  NULL
x_data[[139]] <-  NULL
x_data[[138]] <-  NULL
x_data[[137]] <-  NULL
x_data[[136]] <-  NULL
x_data[[135]] <-  NULL
x_data[[134]] <-  NULL
x_data[[133]] <-  NULL
x_data[[132]] <-  NULL
x_data[[131]] <-  NULL
x_data[[130]] <-  NULL
x_data[[129]] <-  NULL
x_data[[128]] <-  NULL
x_data[[121]] <-  NULL
x_data[[120]] <-  NULL
x_data[[119]] <-  NULL
x_data[[118]] <-  NULL
x_data[[117]] <-  NULL
x_data[[116]] <-  NULL
x_data[[115]] <-  NULL
x_data[[114]] <-  NULL
x_data[[113]] <-  NULL
x_data[[112]] <-  NULL
x_data[[111]] <-  NULL
x_data[[110]] <-  NULL
x_data[[109]] <-  NULL
x_data[[108]] <-  NULL
x_data[[107]] <-  NULL
x_data[[106]] <-  NULL
x_data[[105]] <-  NULL
x_data[[104]] <-  NULL
x_data[[103]] <-  NULL
x_data[[102]] <-  NULL
x_data[[101]] <-  NULL
x_data[[100]] <-  NULL
x_data[[99]] <-  NULL
x_data[[98]] <-  NULL
x_data[[97]] <-  NULL
x_data[[96]] <-  NULL
x_data[[95]] <-  NULL
x_data[[94]] <-  NULL
x_data[[93]] <-  NULL
x_data[[92]] <-  NULL
x_data[[91]] <-  NULL
x_data[[90]] <-  NULL
x_data[[89]] <-  NULL
x_data[[88]] <-  NULL
x_data[[81]] <-  NULL
x_data[[80]] <-  NULL
x_data[[79]] <-  NULL
x_data[[78]] <-  NULL
x_data[[77]] <-  NULL
x_data[[76]] <-  NULL
x_data[[75]] <-  NULL
x_data[[74]] <-  NULL
x_data[[73]] <-  NULL
x_data[[72]] <-  NULL
x_data[[71]] <-  NULL
x_data[[70]] <-  NULL
x_data[[69]] <-  NULL
x_data[[68]] <-  NULL
x_data[[67]] <-  NULL
x_data[[66]] <-  NULL
x_data[[65]] <-  NULL
x_data[[64]] <-  NULL
x_data[[63]] <-  NULL
x_data[[62]] <-  NULL
x_data[[61]] <-  NULL
x_data[[60]] <-  NULL
x_data[[59]] <-  NULL
x_data[[58]] <-  NULL
x_data[[57]] <-  NULL
x_data[[56]] <-  NULL
x_data[[55]] <-  NULL
x_data[[54]] <-  NULL
x_data[[53]] <-  NULL
x_data[[52]] <-  NULL
x_data[[51]] <-  NULL
x_data[[50]] <-  NULL
x_data[[49]] <-  NULL
x_data[[48]] <-  NULL
x_data[[41]] <-  NULL
x_data[[40]] <-  NULL
x_data[[39]] <-  NULL
x_data[[38]] <-  NULL
x_data[[37]] <-  NULL
x_data[[36]] <-  NULL
x_data[[35]] <-  NULL
x_data[[34]] <-  NULL
x_data[[33]] <-  NULL
x_data[[32]] <-  NULL
x_data[[31]] <-  NULL
x_data[[30]] <-  NULL
x_data[[29]] <-  NULL
x_data[[28]] <-  NULL
x_data[[27]] <-  NULL
x_data[[26]] <-  NULL
x_data[[25]] <-  NULL
x_data[[24]] <-  NULL
x_data[[23]] <-  NULL
x_data[[22]] <-  NULL
x_data[[21]] <-  NULL
x_data[[20]] <-  NULL
x_data[[19]] <-  NULL
x_data[[18]] <-  NULL
x_data[[17]] <-  NULL
x_data[[16]] <-  NULL
x_data[[15]] <-  NULL
x_data[[14]] <-  NULL
x_data[[13]] <-  NULL
x_data[[12]] <-  NULL
x_data[[11]] <-  NULL
x_data[[10]] <-  NULL
x_data[[9]] <-  NULL
x_data[[8]] <-  NULL

# now subset data by activity and then aggregate by subject (6 activities)
walking <- subset(x_data,activity==1)
walking_upstairs <- subset(x_data,activity==2)
walking_downstairs <- subset(x_data,activity==3)
sitting <- subset(x_data,activity==4)
standing <- subset(x_data,activity==5)
laying <- subset(x_data,activity==6)
# make the tables
walkingAgg <- aggregate(walking[,2:87],list(walking$subject),mean)
walking_upstairsAgg <- aggregate(walking_upstairs[,2:87],list(walking_upstairs$subject),mean)
walking_downstairsAgg <- aggregate(walking_downstairs[,2:87],list(walking_downstairs$subject),mean)
sittingAgg <- aggregate(sitting[,2:87],list(sitting$subject),mean)
standingAgg <- aggregate(standing[,2:87],list(standing$subject),mean)
layingAgg <- aggregate(laying[,2:87],list(laying$subject),mean)
#rename first column to subject
colnames(walkingAgg)[1] <- "Subject"
colnames(walking_upstairsAgg)[1] <- "Subject"
colnames(walking_downstairsAgg)[1] <- "Subject"
colnames(sittingAgg)[1] <- "Subject"
colnames(standingAgg)[1] <- "Subject"
colnames(layingAgg)[1] <- "Subject"

# write to files
write.table(walkingAgg,row.name=FALSE,file ="walking.txt")
write.table(walking_upstairsAgg,row.name=FALSE,file ="walking_upstairs.txt")
write.table(walking_downstairsAgg,row.name=FALSE,file ="walking_downstairs.txt")
write.table(sittingAgg,row.name=FALSE,file ="sitting.txt")
write.table(standingAgg,row.name=FALSE,file ="standing.txt")
write.table(layingAgg,row.name=FALSE,file ="laying.txt")
write.table(layingAgg,row.name=FALSE,file ="walking.txt")
colnames(layingAgg)[1] <- "Subject"
